### PR TITLE
TM-1066 fixed

### PR DESCRIPTION
**Pull request by ArekZc**

### CODE REVIEW

**Comment by bua89** [comment]
See comment on [JIRA](https://jira.clearcode.cc/browse/TM-1066?focusedCommentId=94390&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-94390).

**Comment by marnits** [comment]
still broken on iphone 5

**Comment by marnits** [comment]
resolve conflicts

**Comment by ArekZc** [comment]
I checked it too and it looks like it's fixed, can you attach some screenshot ?

**Comment by marnits** [comment]
It's because you set Ready Code Review status, but didn't push your changes. I will check it soon.

**Comment by MarcinMat** [comment]
Changing $window.parent.innerWidth condition to 500px may break a lot of things. Be sure to test it thoroughly.

**Comment by ArekZc** [comment]
@MarcinMat but when not changed on 500px iphone 6plus will be not working

**Comment by kallosz** [comment]
Why we use js for this? Can we do the same in css? @MarcinMat @marnits @ArekZc ?

**Comment by ArekZc** [comment]
no iframe, we can't add some css to other people sites

**Pull request closed without merging**
