### PR TITLE
TM-976 containerjs unit tests

### PR DESCRIPTION
**Pull request by marnits**

### CODE REVIEW

**Comment by ArekZc** [comment]
zrzut ekranu 2015-11-12 o 17 40 40

Test fails

**Comment by ArekZc** [comment]
Build not connected to travis

**Comment by ArekZc** [comment]
Run tests on all browsers crush build

**Comment by marnits** [comment]
I forgot to push last changes! For now there are problems with running tests on Iphone, so I decided to not include mobiles into this tests.

**Pull request merged**
