### PR TITLE
TM-1117

### PR DESCRIPTION
**Pull request by kallosz**

### CODE REVIEW

**Comment by ArekZc** [comment]
Missing variable documentation

**Comment by ArekZc** [comment]
I don't think we use condition api route, because this route is related to container not trigger so it seems that this route is not used

**Comment by ArekZc** [comment]
Reset password & Integration shouldn't be in documentation, we can't use them by external clients

**Comment by ArekZc** [comment]
Every route should have description e.g. "Create trigger for choosen container"

**Comment by ArekZc** [comment]
Every route should example response object, now we only know parameters that we could pass

**Comment by ArekZc** [comment]
format for api is html and json, we don't use html format anywhere i think it not necessary in documentation

**Comment by ArekZc** [comment]
Every parameter should contain description and type

**Comment by ArekZc** [comment]
Websites should be in separate group not in containers

**Comment by ArekZc** [comment]
From user we need to remove reset password route

**Comment by ArekZc** [comment]
@pszostak In container we should be able to change permissions for container by API ?

**Comment by ArekZc** [comment]
Please change commit message, it don't say anything

**Comment by kallosz** [comment]
@ArekZc `Every route should have description e.g. "Create trigger for choosen container"` yes I know. But we decide to push this without a description to `1.2` version. But now when we can delay this to `1.2.1` we can add this description.

**Comment by kallosz** [comment]
@ArekZc `Every route should example response object, now we only know parameters that we could pass` this isn't that simple in the current code. I suggest discuss this tomorrow in office.

**Comment by kallosz** [comment]
@ArekZc `Please change commit message, it don't say anything` yes, because I didn't suspect that we need this today to release. This was only draft version.

**Pull request closed without merging**
